import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import HeaderNav from '@/app/components/molecules/headerNav/HeaderNav';
import Footer from '@/app/components/organisms/Footer/Footer';
import '@/app/globals.css';
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }


  return (
    <html lang={locale}>
      <body>
        {/* End Google Analytics */}
        <NextIntlClientProvider locale={locale}>
          <HeaderNav />
          {children}
          <Footer />
        </NextIntlClientProvider>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-DJHG3RS987"
          strategy="afterInteractive"
        />
        {/* Google Analytics */}
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-DJHG3RS987');
          `}
        </Script>
      </body>
    </html>
  );
}
